XXX

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -73,8 +73,9 @@ jobs:
             cd ${PROJECT_DIR}/release/${RELEASE_DIR}
             ls
             pwd
-            make clean || echo "maybe already clean, so if it fails please continue"
+            # make clean || echo "maybe already clean, so if it fails please continue"
             # make ${MODEL} | tee "/tmp/build.log" # | grep -i "error\|-e"
+            mkdir -p ${PROJECT_DIR}/release/${RELEASE_DIR}/image/
             echo "XXX" > ${PROJECT_DIR}/release/${RELEASE_DIR}/image/file.trx
             echo "XXX" > ${PROJECT_DIR}/release/${RELEASE_DIR}/image/file.md5
             echo "CHANGELOG" > /tmp/build.log
